import { parseWorkspace } from "../workspace";
import type { AssetRecord, MorphoWorkspace } from "../types";
import workspaceFixture from "./currentCaseWorkspace.generated.json";
import assetManifestFixture from "./currentCaseAssets.generated.json";
import diagnosticsFixture from "./currentCaseDiagnostics.generated.json";
import { fingerprintCaseStudyWorkspace } from "./caseStudyFingerprint";
import { CURRENT_CASE_STUDY_ID } from "./currentCaseStudyConstants";

export { CURRENT_CASE_STUDY_ID } from "./currentCaseStudyConstants";
export const CURRENT_CASE_STUDY_VERSION = diagnosticsFixture.caseStudyVersion;
export const CURRENT_CASE_STUDY_ASSET_MANIFEST_VERSION = assetManifestFixture.manifestVersion;

export type CurrentCaseStudyAssetManifestEntry = {
  assetId: string;
  contentHash: string;
  mimeType: string;
  publicPath: string;
  runtimeStorageKey: string;
  size: number;
};

export type CurrentCaseStudyAssetManifest = {
  manifestVersion: string;
  assets: CurrentCaseStudyAssetManifestEntry[];
};

export const currentCaseStudyAssetManifest: CurrentCaseStudyAssetManifest = assetManifestFixture;

// The JSON fixtures are generated by npm run case-study:import and are not hand-edited.
const parsedWorkspace = parseWorkspace(JSON.stringify(workspaceFixture));

if (parsedWorkspace.status === "failed") {
  throw new Error(`Current case study workspace is invalid: ${parsedWorkspace.reason}`);
}

if (parsedWorkspace.workspace.project.id !== CURRENT_CASE_STUDY_ID) {
  throw new Error("Current case study workspace does not use the stable project id.");
}

export const currentCaseStudyWorkspace: MorphoWorkspace = parsedWorkspace.workspace;
export const CURRENT_CASE_STUDY_FINGERPRINT = fingerprintCaseStudyWorkspace(currentCaseStudyWorkspace);

export function getCurrentCaseStudyAssets(): Record<string, AssetRecord> {
  return currentCaseStudyWorkspace.assets;
}
